version: "3.9"

services:
  web:
    build: ./backend/
    ports:
      - "5000:5000"
    volumes:
      - "./app.py:/home/app.py"
      - "./static/:/home/static"
      - "./templates:/home/templates"
    env_file:
      - env.dev
    links:
      - database:everything
    depends_on: 
      - database

  database:
    build:
      ./database/
    ports:
      - "3306:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_PASSWORD=supersecretpasswd"
    volumes: 
      - "/mysql:/docker-entrypoint-initdb.d"

  