version: "3.9"

services:
  web:
    build: ./backend/
    ports:
      - "5000:5000"
    volumes:
      - "./app.py:/home/app.py"
      - "./static/:/home/static"
      - "./templates:/home/templates"
      - "./localhost.crt:/home/localhost.crt"
      - "./localhost.key:/home/localhost.key"
    env_file:
      - env.dev
    links:
      - database:everything
    depends_on: 
      - database
    restart: always

  database:
    build:
      ./database/
    ports:
      - "3306:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_PASSWORD=supersecretpasswd"
    volumes: 
      - "./database/mysql/:/docker-entrypoint-initdb.d"
  prometheus:
    image: prom/prometheus
    ports: 
      - "9091:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - config.monitoring  

  