global:
  scrape_interval:     10s
  evaluation_interval: 30s
scrape_configs:
- job_name: 'flask-app'
  scrape_interval: 5s
  static_configs:
  - targets: ['host.docker.internal:5000']
  scheme: https
  tls_config:
    insecure_skip_verify: true
